### ISSUE TITLE
Remove API key

### ISSUE THREAD

**Issue by protzman** [AliceR/react-mapboxgl-example#1]
Not a super huge deal but you may want to remove the api key from your example, and replace with something like `//your api key here`

**Comment by AliceR** [comment]
Thank you for caring!
I don't think it is worth introducing more complexity with env variables here - and I want to be able to deploy the example. If one is interested in using someone else's access token they can read it from any mapbox map using the dev tools, anyways. Wouldn't recommend it for production ;)
